server:
  port: 8082

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - AddRequestHeader=X-GATEWAY, true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
  instance:
    preferIpAddress: true